name: Phone home to report status
description: Reports the workflow status to the dispatcher
inputs:
  phone-home-input:
    description: Metadata to phone-home
    type: string
    required: true
  target-url:
    decription: Override the status URL
    type: string
    required: false
    default: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  state:
    description: Override the state
    type: string
    required: false
  description:
    description: Override the description
    type: string
    required: false
  context:
    description: Override the context
    type: string
    required: false

runs:
  using: node20
  main: main/main.js
  post: post/post.js
